steps:
  # Install dependencies
  - name: 'python:3.12.3'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  - name: 'python:3.12.3'
    entrypoint: python3
    args:
      - '-m'
      - 'compileall'
      - '-f'
      - '-q'
      - '.'
      - '-x'
      - 'venv|__pycache__|\\.ipynb_checkpoints'

  # Deploy Firebase Functions
  - name: 'gcr.io/firebase-tools'
    args: ['deploy', '--only', 'functions']
    env:
      - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_TOKEN: ''  # Will be set in Cloud Build trigger

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/logs'
    paths: ['cloudbuild-logs.txt'] 